modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Aminoquiz/polymorphic_ae2/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="Aminoquiz"
displayURL="https://github.com/Aminoquiz/polymorphic_ae2"
description='''
Adds Polymorph+ recipe-conflict resolution to the Applied Energistics 2 crafting and pattern encoding terminals.
'''

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="${polymorph_mod_id}"
    type="required"
    versionRange="${polymorph_version_range}"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="ae2"
    type="required"
    versionRange="${ae2_version_range}"
    ordering="AFTER"
    side="BOTH"
